# coding: utf-8

"""
    1Password Connect

    REST API interface for 1Password Connect.

    The version of the OpenAPI document: 1.5.7
    Contact: support@1password.com
    Created by: https://support.1password.com/
"""

from 1_password_connect_python_sdk.paths.vaults_vault_uuid_items_item_uuid_files.get import GetAllFilesInsideItem
from 1_password_connect_python_sdk.paths.vaults_vault_uuid_items_item_uuid_files_file_uuid_content.get import GetContent
from 1_password_connect_python_sdk.paths.vaults_vault_uuid_items_item_uuid_files_file_uuid.get import GetFileDetails
from 1_password_connect_python_sdk.apis.tags.files_api_raw import FilesApiRaw


class FilesApi(
    GetAllFilesInsideItem,
    GetContent,
    GetFileDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FilesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FilesApiRaw(api_client)
