# coding: utf-8

"""
    1Password Connect

    REST API interface for 1Password Connect.

    The version of the OpenAPI document: 1.5.7
    Contact: support@1password.com
    Created by: https://support.1password.com/
"""

from 1_password_connect_python_sdk.paths.vaults_vault_uuid_items.post import CreateNewItem
from 1_password_connect_python_sdk.paths.vaults_vault_uuid_items_item_uuid.delete import DeleteItemById
from 1_password_connect_python_sdk.paths.vaults_vault_uuid_items.get import GetAll
from 1_password_connect_python_sdk.paths.vaults_vault_uuid_items_item_uuid.get import GetDetailsById
from 1_password_connect_python_sdk.paths.vaults_vault_uuid_items_item_uuid.put import UpdateItemDetails
from 1_password_connect_python_sdk.paths.vaults_vault_uuid_items_item_uuid.patch import UpdateSubsetAttributes
from 1_password_connect_python_sdk.apis.tags.items_api_raw import ItemsApiRaw


class ItemsApi(
    CreateNewItem,
    DeleteItemById,
    GetAll,
    GetDetailsById,
    UpdateItemDetails,
    UpdateSubsetAttributes,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ItemsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ItemsApiRaw(api_client)
