# coding: utf-8

"""
    1Password Connect

    REST API interface for 1Password Connect.

    The version of the OpenAPI document: 1.5.7
    Contact: support@1password.com
    Created by: https://support.1password.com/
"""

from 1_password_connect_python_sdk.paths.metrics.get import QueryServerMetrics
from 1_password_connect_python_sdk.apis.tags.metrics_api_raw import MetricsApiRaw


class MetricsApi(
    QueryServerMetrics,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MetricsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MetricsApiRaw(api_client)
