# coding: utf-8

"""
    1Password Connect

    REST API interface for 1Password Connect.

    The version of the OpenAPI document: 1.5.7
    Contact: support@1password.com
    Created by: https://support.1password.com/
"""

from 1_password_connect_python_sdk.paths.vaults_vault_uuid.get import GetDetails
from 1_password_connect_python_sdk.paths.vaults.get import ListAll
from 1_password_connect_python_sdk.apis.tags.vaults_api_raw import VaultsApiRaw


class VaultsApi(
    GetDetails,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VaultsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VaultsApiRaw(api_client)
