# coding: utf-8

"""
    1Password Connect

    REST API interface for 1Password Connect.

    The version of the OpenAPI document: 1.5.7
    Contact: support@1password.com
    Created by: https://support.1password.com/
"""

from 1_password_connect_python_sdk.paths.vaults_vault_uuid.get import GetDetailsRaw
from 1_password_connect_python_sdk.paths.vaults.get import ListAllRaw


class VaultsApiRaw(
    GetDetailsRaw,
    ListAllRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
